//
//  CartonBoxUser.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class CartonBoxUser: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _userName: String?
    var _dob: String?
    var _email: String?
    var _gender: String?
    var _mobile: String?
    var _country: String?
    var _createdOn: String?
    var _modifiedOn: String?
    var _active: NSNumber?
    
    class func dynamoDBTableName() -> String {
        return DynamoDB.CartonBoxUser
    }
    
    class func hashKeyAttribute() -> String {
        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_userName" : "userName",
               "_dob" : "dob",
               "_email" : "email",
               "_gender" : "gender",
               "_mobile" : "mobile",
               "_country" : "country",
               "_createdOn": "createdOn",
               "_modifiedOn": "modifiedOn",
               "_active": "active"
        ]
    }
}
