//
//  CartonBoxUserActivity.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class CartonBoxUserActivity: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _activityId: String?
    var _action: String?
    var _createdOn: String?
    var _linkUrl: String?
    var _message: String?
    var _status: NSNumber?
    var _type: String?
    
    class func dynamoDBTableName() -> String {

        return "cartonbox-mobilehub-705934583-CartonBoxUserActivity"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_activityId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_activityId" : "activityId",
               "_action" : "action",
               "_createdOn" : "createdOn",
               "_linkUrl" : "linkUrl",
               "_message" : "message",
               "_status" : "status",
               "_type" : "type",
        ]
    }
}
