//
//  User.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class User: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _active: NSNumber?
    var _country: String?
    var _createdOn: String?
    var _dob: String?
    var _email: String?
    var _gender: String?
    var _mobile: String?
    var _modifiedOn: String?
    var _sourceProvider: String?
    var _userName: String?
    
    class func dynamoDBTableName() -> String {

        return "cartonbox-mobilehub-2074369928-User"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_active" : "active",
               "_country" : "country",
               "_createdOn" : "createdOn",
               "_dob" : "dob",
               "_email" : "email",
               "_gender" : "gender",
               "_mobile" : "mobile",
               "_modifiedOn" : "modifiedOn",
               "_sourceProvider" : "sourceProvider",
               "_userName" : "userName",
        ]
    }
}
